classDiagram

class init_classes {
Fn
}

main ..> init_classes

class get_rust_files {
Fn
}

main ..> get_rust_files

class parse_rust_file {
Fn
}

main ..> parse_rust_file

class MermaidDiagram {
Trait
+to_diagram_syntax() String
}

Relationship <|-- MermaidDiagram
Class <|-- MermaidDiagram
Function <|-- MermaidDiagram
Connection <|-- MermaidDiagram
Field <|-- MermaidDiagram
Visibility <|-- MermaidDiagram

class find_relationships {
Fn
}

main ..> find_relationships

class check_tokens {
Fn
}

check_tokens ..> check_tokens
find_relationships ..> check_tokens

class check_token {
Fn
}

check_tokens ..> check_token

class create_connection {
Fn
}

check_token ..> create_connection

class Class {
Struct
~_visibility: Visibility
~type_: String
~name: String
~fields: Vec < Field >
~functions: Vec < Function >
~connections: HashMap < String , Connection >
+new() Self
+add_connection() 
}

Class --> Function
Class --> Visibility
find_relationships ..> Class
Class --> Field
init_classes ..> Class
Class --> Connection

class Field {
Struct
~visibility: Visibility
~name: String
~type_string: String
+new() Self
}

Field --> Visibility
Field ..> Visibility
init_classes ..> Field

class Function {
Struct
~visibility: Visibility
~name: String
~params: String
~return_type: String
+new() Self
}

init_classes ..> Function
Function ..> Visibility
Function --> Visibility
find_relationships ..> Function

class Connection {
Struct
~name_a: String
~name_b: String
~relationship: Relationship
+new() Self
}

Connection ..> Relationship
create_connection ..> Connection
find_relationships ..> Connection
Connection --> Relationship

class Relationship {
Enum
+Inheritance: 
+Association: 
+Dependency: 
}

find_relationships ..> Relationship
create_connection ..> Relationship

class Visibility {
Enum
+Public: 
+Private: 
+Internal: 
+from_vis() Self
}

find_relationships ..> Visibility
init_classes ..> Visibility

class Settings {
Struct
+image_settings: ImageSettings
+diagram_settings: DiagramSettings
+defaults() Self
}

main ..> Settings
Settings --> DiagramSettings
Settings --> ImageSettings
start_lsp_servers ..> Settings

class ImageSettings {
Struct
+_enabled: bool
+scale: u32
}


class DiagramSettings {
Struct
+show_parameters: bool
}

MermaidDiagram ..> DiagramSettings

class main {
Fn
}


class start_lsp_servers {
Fn
}

main ..> start_lsp_servers

class start_lsp_server {
Fn
}

start_lsp_servers ..> start_lsp_server

