classDiagram

class init_classes {
Fn
}

main ..> init_classes

class get_rust_files {
Fn
}

main ..> get_rust_files

class parse_rust_file {
Fn
}

main ..> parse_rust_file

class MermaidDiagram {
Trait
+to_diagram_syntax() String
}

Connection <|-- MermaidDiagram
Field <|-- MermaidDiagram
Function <|-- MermaidDiagram
Relationship <|-- MermaidDiagram
Class <|-- MermaidDiagram
Visibility <|-- MermaidDiagram

class find_relationships {
Fn
}

main ..> find_relationships

class eval_statements {
Fn
}

eval_expr ..> eval_statements
find_relationships ..> eval_statements

class eval_arms {
Fn
}

eval_expr ..> eval_arms

class eval_exprs {
Fn
}

eval_expr ..> eval_exprs

class eval_expr {
Fn
}

eval_arms ..> eval_expr
eval_exprs ..> eval_expr
eval_expr ..> eval_expr
eval_statements ..> eval_expr

class check_connection {
Fn
}

eval_statements ..> check_connection
eval_expr ..> check_connection

class Class {
Struct
~visibility: Visibility
~type_: String
~name: String
~fields: Vec < Field >
~functions: Vec < Function >
~connections: HashMap < String , Connection >
+new() Self
+add_connection() 
}

Class --> Field
init_classes ..> Class
Class --> Visibility
Class --> Function
find_relationships ..> Class
Class --> Connection

class Field {
Struct
~visibility: Visibility
~name: String
~type_string: String
+new() Self
}

Field ..> Visibility
Field --> Visibility

class Function {
Struct
~visibility: Visibility
~name: String
~params: String
~return_type: String
+new() Self
}

Function ..> Visibility
Function --> Visibility

class Connection {
Struct
~name_a: String
~name_b: String
~relationship: Relationship
+new() Self
}

Connection ..> Relationship
find_relationships ..> Connection
check_connection ..> Connection
Connection --> Relationship

class Relationship {
Enum
+Inheritance: 
+Association: 
+Dependency: 
}


class Visibility {
Enum
+Public: 
+Private: 
+Internal: 
+from_vis() Self
}

init_classes ..> Visibility
find_relationships ..> Visibility

class Settings {
Struct
+image_settings: ImageSettings
+diagram_settings: DiagramSettings
+defaults() Self
}

main ..> Settings
Settings --> ImageSettings
Settings --> DiagramSettings

class ImageSettings {
Struct
+enabled: bool
+scale: u32
}


class DiagramSettings {
Struct
+show_parameters: bool
}

MermaidDiagram ..> DiagramSettings

class main {
Fn
}


